version: '3.9'

services:
  web:
    container_name: web
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
      - db
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=SmartSofts
      
